AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "lib/chain_mail/helpers/sendpulse_api.rb"

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "chain_mail.gemspec"

Metrics/MethodLength:
  Max: 35

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
